version: '3.8'

services:
  private-vault:
    build: .
    container_name: private-vault
    ports:
      - "8080:80"
    volumes:
      - ./api:/var/www/html/api
    restart: unless-stopped

# TheKom™ // was here.
